// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASiyl514Rvyq3Iu5DAJtGsB7UH4p5xFag',
    appId: '1:540506569066:web:3d9d8d3444fae291240d13',
    messagingSenderId: '540506569066',
    projectId: 'first-app-2004',
    authDomain: 'first-app-2004.firebaseapp.com',
    databaseURL: 'https://first-app-2004-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-2004.firebasestorage.app',
    measurementId: 'G-Q6BGFP8DRD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEcm0NwM1LM847KsuaL4YcpfGl-rPbHxU',
    appId: '1:540506569066:android:4cd1b19f67afff2e240d13',
    messagingSenderId: '540506569066',
    projectId: 'first-app-2004',
    databaseURL: 'https://first-app-2004-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-2004.firebasestorage.app',
  );
}
